# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "namln-app"
client_id = "abb5d03a35ff0067ce6ea7a53bfdfdff"
application_url = "https://worldcat-marathon-urls-dust.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://worldcat-marathon-urls-dust.trycloudflare.com/auth/callback",
  "https://worldcat-marathon-urls-dust.trycloudflare.com/auth/shopify/callback",
  "https://worldcat-marathon-urls-dust.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "namln-training-store.myshopify.com"
